apiVersion: v1
kind: Service
metadata:
  name: mssql-demo-svc-external
  namespace: arc
spec:
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
  selector:
    app: demo-app
  type: NodePort
